# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Viresh
tagline:          'A S'
description:      'Software Engineer. <a href="https://github.com/vireshas" target="_blank">Github</a>, <a href="https://twitter.com/vireshas" target="_blank">Twitter</a>'
url:              https://vireshas.github.io
baseurl:          /

author:
  name:           'Viresh A S'
  url:            https://twitter.com/vireshas

paginate:         5

github:
  repo:           https://github.com/vireshas/vireshas.github.com
