# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Viresh
tagline:          'S'
description:      'Software Engineer. <a href="https://github.com/vireshas" target="_blank">@Github</a>, <a href="https://twitter.com/vireshas" target="_blank">@twitter</a>'
url:              https://vireshas.github.io
baseurl:          /

author:
  name:           'Viresh A S'
  url:            https://twitter.com/vireshas

paginate:         1

github:
  repo:           https://github.com/vireshas/vireshas.github.com
